import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Owner-only chat assistant for questions about business figures.
/// Answers are generated by the owner-ai-assistant Supabase Edge Function.
class OwnerAIAssistantScreen extends StatefulWidget {
  const OwnerAIAssistantScreen({super.key});

  @override
  State<OwnerAIAssistantScreen> createState() => _OwnerAIAssistantScreenState();
}

class _OwnerAIAssistantScreenState extends State<OwnerAIAssistantScreen> {
  final SupabaseClient _supabase = Supabase.instance.client;
  final TextEditingController _questionController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  final List<_AssistantMessage> _messages = [
    _AssistantMessage(
      text:
          "Hi! I'm your business assistant. Ask me about today's collection, sales, outstanding balances, recent payments, or your top customers.",
      isUser: false,
    ),
  ];

  bool _sending = false;

  static const List<String> _suggestions = [
    "How much is today's collection?",
    "How much did we sell today?",
    "What is the total outstanding?",
    "Show the latest payments",
    "Which customers owe the most?",
  ];

  @override
  void dispose() {
    _questionController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  Future<void> _sendQuestion([String? suggested]) async {
    if (_sending) return;
    final question = (suggested ?? _questionController.text).trim();
    if (question.isEmpty) return;

    setState(() {
      _messages.add(_AssistantMessage(text: question, isUser: true));
      _questionController.clear();
      _sending = true;
    });
    _scrollToBottom();

    try {
      final response = await _supabase.functions.invoke(
        'owner-ai-assistant',
        body: <String, dynamic>{'question': question},
      );

      final data = response.data;
      if (response.status < 200 || response.status >= 300) {
        final message = data is Map
            ? (data['error'] ?? 'The assistant request failed.').toString()
            : 'The assistant request failed (HTTP ${response.status}).';
        throw Exception(message);
      }
      if (data is! Map || data['answer'] == null) {
        throw const FormatException(
          'The assistant returned an unexpected response.',
        );
      }

      final answer = data['answer'].toString();
      if (mounted) {
        setState(() {
          _messages.add(_AssistantMessage(text: answer, isUser: false));
        });
      }
    } catch (error) {
      if (mounted) {
        setState(() {
          _messages.add(
            _AssistantMessage(
              text: _friendlyError(error),
              isUser: false,
              isError: true,
            ),
          );
        });
      }
    } finally {
      if (mounted) setState(() => _sending = false);
      _scrollToBottom();
    }
  }

  String _friendlyError(Object error) {
    var message = error.toString().replaceFirst('Exception: ', '');
    message = message.replaceFirst('FormatException: ', '');
    if (message.contains('GEMINI_API_KEY') ||
        message.contains('AI is not configured')) {
      return 'AI is not configured yet. Check the GEMINI_API_KEY secret in your Supabase Edge Function settings.';
    }
    if (message.contains('Failed to fetch') ||
        message.contains('SocketException')) {
      return 'I could not connect. Check your internet connection and try again.';
    }
    return message;
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!_scrollController.hasClients) return;
      _scrollController.animateTo(
        _scrollController.position.maxScrollExtent,
        duration: const Duration(milliseconds: 250),
        curve: Curves.easeOut,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Business AI Assistant'),
        actions: [
          IconButton(
            tooltip: 'Clear conversation',
            onPressed: _sending
                ? null
                : () => setState(() {
                    _messages
                      ..clear()
                      ..add(
                        _AssistantMessage(
                          text:
                              "Conversation cleared. What would you like to know about your business?",
                          isUser: false,
                        ),
                      );
                  }),
            icon: const Icon(Icons.refresh),
          ),
        ],
      ),
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: ListView(
                controller: _scrollController,
                padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
                children: [
                  if (_messages.length == 1) ...[
                    Text(
                      'Ask in your own words',
                      style: theme.textTheme.titleMedium,
                    ),
                    const SizedBox(height: 10),
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: _suggestions
                          .map(
                            (question) => ActionChip(
                              label: Text(question),
                              onPressed: _sending
                                  ? null
                                  : () => _sendQuestion(question),
                            ),
                          )
                          .toList(),
                    ),
                    const SizedBox(height: 18),
                  ],
                  ..._messages.map((message) => _buildMessage(message, theme)),
                  if (_sending)
                    const Padding(
                      padding: EdgeInsets.only(top: 8, bottom: 16),
                      child: Align(
                        alignment: Alignment.centerLeft,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            ),
                            SizedBox(width: 10),
                            Text('Checking your business figures…'),
                          ],
                        ),
                      ),
                    ),
                ],
              ),
            ),
            const Divider(height: 1),
            Padding(
              padding: const EdgeInsets.fromLTRB(12, 10, 12, 12),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  Expanded(
                    child: TextField(
                      controller: _questionController,
                      minLines: 1,
                      maxLines: 5,
                      textInputAction: TextInputAction.send,
                      onSubmitted: (_) => _sendQuestion(),
                      enabled: !_sending,
                      decoration: InputDecoration(
                        hintText: 'Ask about today’s collection…',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(22),
                        ),
                        contentPadding: const EdgeInsets.symmetric(
                          horizontal: 16,
                          vertical: 12,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  IconButton.filled(
                    tooltip: 'Send question',
                    onPressed: _sending ? null : () => _sendQuestion(),
                    icon: const Icon(Icons.send_rounded),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildMessage(_AssistantMessage message, ThemeData theme) {
    final alignment = message.isUser
        ? Alignment.centerRight
        : Alignment.centerLeft;
    final color = message.isUser
        ? theme.colorScheme.primaryContainer
        : message.isError
        ? theme.colorScheme.errorContainer
        : theme.colorScheme.surfaceContainerHighest;
    final textColor = message.isUser
        ? theme.colorScheme.onPrimaryContainer
        : message.isError
        ? theme.colorScheme.onErrorContainer
        : theme.colorScheme.onSurface;
    return Align(
      alignment: alignment,
      child: Container(
        constraints: const BoxConstraints(maxWidth: 620),
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 12),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(18),
        ),
        child: SelectableText(
          message.text,
          style: theme.textTheme.bodyMedium?.copyWith(
            color: textColor,
            height: 1.35,
          ),
        ),
      ),
    );
  }
}

class _AssistantMessage {
  const _AssistantMessage({
    required this.text,
    required this.isUser,
    this.isError = false,
  });

  final String text;
  final bool isUser;
  final bool isError;
}
